# Generated by Django 5.1.6 on 2025-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(choices=[('new', 'Like New'), ('written', 'Written In'), ('old', 'Old')], max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
